version: '3.7'

services:
  web:
    build: &web ./app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app
    ports:
      - 8000:8000
    env_file: &envfile ./.env.dev

  db:
    image: postgres:11.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=application_database
      - POSTGRES_USER=application_database

  rabbitmq:
    image: rabbitmq:3.7.8

  redis:
    image: redis:alpine

  celery:
    build: *web
    command: ["celery", "worker", "-A", "boilerplate", "--loglevel", "INFO"]
    volumes:
      - ./app/:/usr/src/app
    env_file: *envfile
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_data: